### ISSUE TITLE
Converting lat./long. datatype to double for higher precision

### ISSUE THREAD

**Issue by williambogaiv** [ritterim/atlas#1]
https://github.com/ritterim/atlas/blob/d8013a18f528f1e7b58efb60d1c154814b56c69d/src/Atlas/ZipCode.cs#L11 uses `float` based on existing coord.-data (https://github.com/ritterim/atlas/blob/d8013a18f528f1e7b58efb60d1c154814b56c69d/common/ZipCodes.csv), but `double` would afford more precision if this data gets updated in the future without causing child-apps. to be updated.

Please note, however, the distance-differences would be under one-hundred feet for both lat. and long.
Given a second of lat. (1" = 1/3600 = 0.000277778) is constant at roughly one-hundred feet (http://nationalatlas.gov/articles/mapping/a_latlong.html) and any precision gains for lat. would be to the right of a float's max. precision:
```
12.345678f = 12.34568
12.345674f = 12.34567

12.34568 - 12.34567 = 0.00001 // 0.036 lat. sec. ~ 3.6 ft.
```
Long. secs. are not constant (are dependent on lat. position), but empirical data (based on PA-lat.) shows similar distances between secs. and again would only have maximum impact if mid-west and westward U.S. zip-codes are used (since mid-west long. have triple-digit degrees).

**Comment by khalidabuhakmeh** [comment]
Won't Fix.
