### ISSUE TITLE
Missing zip codes - 75033 and 21764

### ISSUE THREAD

**Issue by lightyeare** [ritterim/atlas#14]
@JCarver27 commented on [Tue Nov 02 2021](https://github.com/ritterim/tide/issues/627)

## 🐛 Bug Report
We're missing a zip code in Tide....75033.

## To Reproduce

1. Go to https://tide.rimdev.io/lead-workflow/new?callDirection=Inbound&stepId=InboundPreLandingViewModel
2. Fill in first, last, and phone number. I recommend something ridiculous, because why not.
3. Enter 75033 as the zip on the next screen

## Expected behavior
75033 is a valid zip in TX.

## Screenshots and/or request snippets

![2021-11-02 09_41_01-Ritter IM -](https://user-images.githubusercontent.com/13123555/139858370-147d4ac0-24ea-4382-8310-8ce34d91e660.png)

## Estimates

---

@JCarver27 commented on [Tue Nov 02 2021](https://github.com/ritterim/tide/issues/627#issuecomment-957602958)

21764 is also showing an error.

![2021-11-02 09_42_57-Ritter IM -](https://user-images.githubusercontent.com/13123555/139858706-75f822f3-e8a7-4b42-9f8d-3376d8029795.png)

---

@lightyeare commented on [Tue Nov 02 2021](https://github.com/ritterim/tide/issues/627#issuecomment-957812486)

Uses Ritter.Atlas, which hasn't been updated in a while.

![image](https://user-images.githubusercontent.com/2921868/139876555-4ca204a3-8239-43de-b04d-f7b665aa732a.png)

---

@bwarner22 commented on [Wed Nov 03 2021](https://github.com/ritterim/tide/issues/627#issuecomment-958971097)

Ritter.Atlas ???? didn't know we had such a thing!

**Comment by JCarver27** [comment]
Confirmed in dev
