### ISSUE TITLE
Additional Information To Add to Csv Data

### ISSUE THREAD

**Issue by lightyeare** [ritterim/atlas#6]
Atlas is missing:
- Elevation
- Primary City (which I think is the largest city in the zip code)
- ScfCode

However, ScfCode can be easily derived from the zip code. The ScfCode is the first three digits of the zip code.

Atlas includes the AnsiCodes for County and State.

**Comment by khalidabuhakmeh** [comment]
@lightyeare I updated the issue and contents to be more aware of the fact that this is an OSS project :).

**Comment by khalidabuhakmeh** [comment]
@kricords Could you confirm whether we have this additional data in your dataset?

**Comment by kricords** [comment]
Files sent @khalidabuhakmeh with elevation and primary city appended to Counties.csv

--Counties
select distinct [StateCode]=State,[Name]=County,[AnsiCode]=CountyANSI,[FipsCode]=CountyFIPS
from dbo.ZipCodes z
order by State,CountyFIPS

--CountyZipCodes
select distinct [StateCode]=coalesce(m.State,z.State),[Name]=coalesce(m.County,z.County),z.ZipCode
from dbo.ZipCodes z
	left outer join dbo.ZipCodesMultiCounty m on( z.ZipCode=m.ZipCode )
order by z.ZipCode

--States
select distinct [StateCode]=State,[Name]=StateFullName,AnsiCode=StateANSI,FipsCode=StateFIPS
from ZipCodes
order by State

--ZipCodes
select distinct StateCode=coalesce(m.State,z.State),z.ZipCode,Latitude,Longitude,Elevation,TimeZone,PrimaryCity=City
from ZipCodes z
	left outer join dbo.ZipCodesMultiCounty m on( z.ZipCode=m.ZipCode )
order by z.ZipCode

**Comment by khalidabuhakmeh** [comment]
:congratulations: closing
