### ISSUE TITLE
Update data 

### ISSUE THREAD

**Issue by lightyeare** [ritterim/atlas#9]
We have data for March 2015. 

[Counties](https://ritterim.slack.com/files/chad.peters/F047D45U7/counties.csv)
[CountyZipCode](https://ritterim.slack.com/files/chad.peters/F047D4RPX/countyzipcodes.csv)
[States](https://ritterim.slack.com/files/chad.peters/F046PGG3E/states.csv)
[ZipCodes](https://slack-files.com/T03G9RUH9-F046PGVMN-4a5c93da2f)

hmmm...not sure if i created these links right

**Comment by khalidabuhakmeh** [comment]
:+1:
